server {
     listen 443 ssl; 
     server_name zhongdang.net;
     ssl_certificate zhongdang.net_bundle.crt;
     ssl_certificate_key zhongdang.net.key; 
     ssl_session_timeout 5m;
     ssl_protocols TLSv1.2 TLSv1.3;
     ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE; 
     ssl_prefer_server_ciphers on;
     location / {
         root /home/ubuntu/web; 
         index  index.html;
     }
 }
